FROM python:3.10-slim

# Install build dependencies for asyncpg and other C extensions
RUN apt-get update && apt-get install -y build-essential libffi-dev gcc python3-dev

WORKDIR /dspback

COPY requirements.txt requirements.txt
COPY requirements-dev.txt requirements-dev.txt

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

ENV PYTHONPATH "${PYTHONPATH}:/"

CMD ["python", "dspback/main.py"]
