# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2022-03-09T17:44:04+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import AnyUrl, BaseModel, EmailStr, Field, confloat, constr


class Creator(BaseModel):
    name: Optional[constr(max_length=100)] = Field(
        None, description='A string containing the name of the creator', title='Name'
    )
    phone: Optional[constr(max_length=25)] = Field(
        None,
        description='A string containing a phone number for the creator',
        title='Phone',
    )
    address: Optional[constr(max_length=250)] = Field(
        None,
        description='A string containing an address for the creator',
        title='Address',
    )
    organization: Optional[constr(max_length=200)] = Field(
        None,
        description='A string containing the name of the organization with which the creator is affiliated',
        title='Organization',
    )
    email: Optional[EmailStr] = Field(
        None,
        description='A string containing an email address for the creator',
        title='Email',
    )
    homepage: Optional[AnyUrl] = Field(
        None,
        description='An object containing the URL for website associated with the creator',
        title='Homepage',
    )
    description: Optional[constr(max_length=50)] = Field(
        None,
        description='A string containing the path to the hydroshare profile',
        title='HydroShare Profile',
    )


class Contributor(BaseModel):
    name: Optional[str] = Field(
        None,
        description='A string containing the name of the contributor',
        title='Name',
    )
    phone: Optional[str] = Field(
        None,
        description='A string containing a phone number for the contributor',
        title='Phone',
    )
    address: Optional[str] = Field(
        None,
        description='A string containing an address for the contributor',
        title='Address',
    )
    organization: Optional[str] = Field(
        None,
        description='A string containing the name of the organization with which the contributor is affiliated',
        title='Organization',
    )
    email: Optional[EmailStr] = Field(
        None,
        description='A string containing an email address for the contributor',
        title='Email',
    )
    homepage: Optional[AnyUrl] = Field(
        None,
        description='An object containing the URL for website associated with the contributor',
        title='Homepage',
    )
    description: Optional[constr(max_length=50)] = Field(
        None,
        description='A string containing the path to the hydroshare profile',
        title='Description',
    )


class RelationType(Enum):
    The_content_of_this_resource_is_part_of = 'The content of this resource is part of'
    This_resource_includes = 'This resource includes'
    The_content_of_this_resource_was_created_by_a_related_App_or_software_program = (
        'The content of this resource was created by a related App or software program'
    )
    The_content_of_this_resource_was_created_by = (
        'The content of this resource was created by'
    )
    This_resource_updates_and_replaces_a_previous_version = (
        'This resource updates and replaces a previous version'
    )
    This_resource_has_been_replaced_by_a_newer_version = (
        'This resource has been replaced by a newer version'
    )
    This_resource_is_described_by = 'This resource is described by'
    This_resource_conforms_to_established_standard_described_by = (
        'This resource conforms to established standard described by'
    )
    This_resource_has_a_related_resource_in_another_format = (
        'This resource has a related resource in another format'
    )
    This_resource_is_a_different_format_of = 'This resource is a different format of'
    This_resource_is_required_by = 'This resource is required by'
    This_resource_requires = 'This resource requires'
    This_resource_is_referenced_by = 'This resource is referenced by'
    The_content_of_this_resource_references = 'The content of this resource references'
    This_resource_replaces = 'This resource replaces'
    The_content_of_this_resource_is_derived_from = (
        'The content of this resource is derived from'
    )


class Relation(BaseModel):
    type: RelationType = Field(
        ...,
        description='The type of relationship with the related resource',
        title='Relation type',
    )
    value: constr(max_length=500) = Field(
        ...,
        description='String expressing the Full text citation, URL link for, or description of the related resource',
        title='Value',
    )


class AdditionalMetadata(BaseModel):
    key: str = Field(..., title='Key')
    value: str = Field(..., title='Value')


class Rights(BaseModel):
    statement: str = Field(
        ...,
        description='A string containing the text of the license or rights statement',
        title='Statement',
    )
    url: AnyUrl = Field(
        ...,
        description='An object containing the URL pointing to a description of the license or rights statement',
        title='URL',
    )


class AwardInfo(BaseModel):
    funding_agency_name: str = Field(
        ...,
        description='A string containing the name of the funding agency or organization',
        title='Agency name',
    )
    title: Optional[str] = Field(
        None,
        description='A string containing the title of the project or award',
        title='Award title',
    )
    number: Optional[str] = Field(
        None,
        description='A string containing the award number or other identifier',
        title='Award number',
    )
    funding_agency_url: Optional[AnyUrl] = Field(
        None,
        description='An object containing a URL pointing to a website describing the funding award',
        title='Agency URL',
    )


class PointCoverage(BaseModel):
    type: Optional[str] = Field(
        None,
        description='A string containing the type of geographic coverage',
        title='Geographic coverage type',
    )
    name: Optional[str] = Field(
        None,
        description='A string containing a name for the place associated with the geographic coverage',
        title='Name',
    )
    east: confloat(lt=180.0, gt=-180.0) = Field(
        ...,
        description='The coordinate of the point location measured in the east direction',
        title='East',
    )
    north: confloat(lt=90.0, gt=-90.0) = Field(
        ...,
        description='The coordinate of the point location measured in the north direction',
        title='North',
    )
    units: str = Field(
        ...,
        description='The units applying to the unlabelled numeric values of north and east',
        title='Units',
    )
    projection: str = Field(
        ...,
        description='The name of the projection used with any parameters required, such as ellipsoid parameters, datum, standard parallels and meridians, zone, etc.',
        title='Projection',
    )


class BoxCoverage(BaseModel):
    type: Optional[str] = Field(
        None,
        description='A string containing the type of geographic coverage',
        title='Geographic coverage type',
    )
    name: Optional[str] = Field(
        None,
        description='A string containing a name for the place associated with the geographic coverage',
        title='Name',
    )
    northlimit: confloat(lt=90.0, gt=-90.0) = Field(
        ...,
        description='A floating point value containing the constant coordinate for the northernmost face or edge of the bounding box',
        title='North limit',
    )
    eastlimit: confloat(lt=180.0, gt=-180.0) = Field(
        ...,
        description='A floating point value containing the constant coordinate for the easternmost face or edge of the bounding box',
        title='East limit',
    )
    southlimit: confloat(lt=90.0, gt=-90.0) = Field(
        ...,
        description='A floating point value containing the constant coordinate for the southernmost face or edge of the bounding box',
        title='South limit',
    )
    westlimit: confloat(lt=180.0, gt=-180.0) = Field(
        ...,
        description='A floating point value containing the constant coordinate for the westernmost face or edge of the bounding box',
        title='West limit',
    )
    units: str = Field(
        ...,
        description='A string containing the units applying to the unlabelled numeric values of northlimit, eastlimit, southlimit, and westlimit',
        title='Units',
    )
    projection: Optional[str] = Field(
        None,
        description='A string containing the name of the projection used with any parameters required, such as ellipsoid parameters, datum, standard parallels and meridians, zone, etc.',
        title='Projection',
    )


class PeriodCoverage(BaseModel):
    name: Optional[str] = Field(
        None,
        description='A string containing a name for the time interval',
        title='Name',
    )
    start: datetime = Field(
        ...,
        description='A datetime object containing the instant corresponding to the commencement of the time interval',
        title='Start',
    )
    end: datetime = Field(
        ...,
        description='A datetime object containing the instant corresponding to the termination of the time interval',
        title='End',
    )


class Publisher(BaseModel):
    name: constr(max_length=200) = Field(
        ...,
        description='A string containing the name of the publisher',
        title='Publisher name',
    )
    url: AnyUrl = Field(
        ...,
        description='An object containing a URL that points to the publisher website',
        title='Publisher URL',
    )


class ResourceMetadata(BaseModel):
    title: constr(max_length=300) = Field(
        ...,
        description='A string containing the name given to a resource',
        title='Title',
    )
    abstract: str = Field(
        ..., description='A string containing a summary of a resource', title='Abstract'
    )
    subjects: List[str] = Field(
        ...,
        description='A list of keyword strings expressing the topic of a resource',
        title='Subject keywords',
    )
    creators: Optional[List[Creator]] = Field(
        [],
        description='A list of Creator objects indicating the entities responsible for creating a resource',
        title='Creators',
    )
    contributors: Optional[List[Contributor]] = Field(
        [],
        description='A list of Contributor objects indicating the entities that contributed to a resource',
        title='Contributors',
    )
    relations: Optional[List[Relation]] = Field(
        [],
        description='A list of Relation objects representing resources related to a described resource',
        title='Related resources',
    )
    additional_metadata: Optional[List[AdditionalMetadata]] = Field(
        [],
        description='A dictionary containing key-value pair metadata associated with a resource',
        title='Additional metadata',
    )
    rights: Optional[Rights] = Field(
        None,
        description='An object containing information about rights held in an over a resource',
        title='Rights',
    )
    awards: Optional[List[AwardInfo]] = Field(
        [],
        description='A list of objects containing information about the funding agencies and awards associated with a resource',
        title='Funding agency information',
    )
    spatial_coverage: Optional[Union[PointCoverage, BoxCoverage]] = Field(
        None,
        description='An object containing information about the spatial topic of a resource, the spatial applicability of a resource, or jurisdiction under with a resource is relevant',
        title='Spatial coverage',
    )
    period_coverage: Optional[PeriodCoverage] = Field(
        None,
        description='An object containing information about the temporal topic or applicability of a resource',
        title='Temporal coverage',
    )
    publisher: Optional[Publisher] = Field(
        None,
        description='An object containing information about the publisher of a resource',
        title='Publisher',
    )
    citation: Optional[str] = Field(
        None,
        description='A string containing the biblilographic citation for a resource',
        title='Citation',
    )
